# version: '3.9'

# services:
#   backend:
#     build: ./backend
#     ports:
#       - "8000:8000"

#   frontend:
#     image: node:20
#     working_dir: /app
#     ports:
#       - "3000:3000"

#   mongodb:
#     image: mongo:7
#     ports:
#       - "27017:27017"


version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: job_hunter_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local